# Generated by Django 5.2.4 on 2026-01-07 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('citadine', 'Citadine'), ('compacte', 'Compacte'), ('berline', 'Berline'), ('suv', 'SUV'), ('utilitaire', 'Utilitaire')], max_length=50)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20)),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique'), ('hybride', 'Hybride')], default='essence', max_length=20)),
                ('places', models.PositiveSmallIntegerField(default=5)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
            ],
        ),
    ]
