# Generated by Django 5.2.8 on 2025-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['marque', 'modele']},
        ),
        migrations.AddField(
            model_name='vehicule',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='carburant',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique'), ('hybride', 'Hybride')], default='essence', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='places',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='transmission',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='categorie',
            field=models.CharField(choices=[('citadine', 'Citadine'), ('compacte', 'Compacte'), ('berline', 'Berline'), ('suv', 'SUV'), ('utilitaire', 'Utilitaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicules/'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('maintenance', 'Maintenance')], default='disponible', max_length=20),
        ),
    ]
